from typing import Any

INTERFACE_FIELDS: Any

def list_network_interfaces(by: str = ...): ...
def network_interface_info(resource: Any): ...
def get_ipv4_occupied_ports(ip: Any): ...
def get_ipv4_address(resource: Any): ...
