from _typeshed import Incomplete

INTERFACE_FIELDS: Incomplete

def list_network_interfaces(by: str = ...): ...
def network_interface_info(resource): ...
def get_ipv4_occupied_ports(ip): ...
def get_ipv4_address(resource): ...
def find_free_port(): ...
