import labbench as lb
from typing import Any, Optional

class WLANInfo(lb.ShellBackend):
    def __init__(
        self,
        resource: str = "str",
        binary_path: str = "str",
        timeout: str = "int",
        only_bssid: str = "bool",
        interface: str = "NoneType",
    ): ...
    FLAGS: Any = ...
    only_bssid: Any = ...
    interface: Any = ...
    def wait(self) -> None: ...
    def get_wlan_ssids(self, interface: Any): ...
    def get_wlan_interfaces(
        self, name: Optional[Any] = ..., param: Optional[Any] = ...
    ): ...

class WLANClient(lb.Device):
    def __init__(
        self, resource: str = "str", ssid: str = "NoneType", timeout: str = "int"
    ): ...
    resource: Any = ...
    ssid: Any = ...
    timeout: Any = ...
    backend: Any = ...
    def open(self) -> None: ...
    @classmethod
    def list_available_clients(cls, by: str = ...): ...
    @classmethod
    def __imports__(cls) -> None: ...
    def interface_connect(self): ...
    def interface_disconnect(self): ...
    def interface_reconnect(self): ...
    def state(self): ...
    def isup(self): ...
    def transmit_rate_mbps(self): ...
    def signal(self): ...
    def description(self): ...
    def channel(self): ...
    def refresh(self) -> None: ...
