[project]
name = "ssmdevices"
version = "0.9"
description = "a curated set of instrument automation drivers implemented with labbench"

authors = [
    {name = "Dan Kuester", email = "daniel.kuester@nist.gov"},
    {name="Duncan McGillivray", email = "duncan.a.mcgillivray@nist.gov"  },
    {name="Andre Rosete", email = "andre.rosete@nist.gov" },
    {name="Paul Blanchard", email = "paul.blanchard@nist.gov" },
    {name="Michael Voecks", email = "michael.voecks@nist.gov" },
    {name="Ryan Jacobs", email = "ryan.jacobs@nist.gov" },
    {name="Alex Curtin", email =  "alexandra.curtin@nist.gov" },
    {name="Audrey Puls", email = "audrey.puls@nist.gov" },
    {name="John Ladbury", email = "john.ladbury@nist.gov" },
    {name="Yao Ma", email = "yao.ma@nist.gov" }
]

maintainers = [
    {name = "Dan Kuester", email = "daniel.kuester@nist.gov"},
]

dependencies = [
    "labbench>=0.23.4",
    "hidapi",
    "pywifi",
    "brainstem>=2.9.26",
]

requires-python = ">=3.7"
readme = "README.md"
license = {file = "LICENSE.md"}

[project.urls]
homepage = "https://github.com/usnistgov/ssmdevices"
repository = "https://github.com/usnistgov/ssmdevices"
documentation = "https://pages.nist.gov/ssmdevices"

[build-system]
requires = [
    "pdm-pep517>=1.0",
]
build-backend = "pdm.pep517.api"

[tool]
[tool.pdm]

[tool.pdm.dev-dependencies]
lint = [
    "flake8",
    "black",
    "ast_decompiler",
    "mypy",
]
test = ["pytest", "pytest-cov"]
doc = ["sphinx>=1.6", "recommonmark"]
tools = ["ipython", "jupyter"]

[tool.black]
line-length = 88
target-version = ["py37", "py38", "py39", "py310", "py311"]
include = '\.pyi?$'