[project]
name = "ssmdevices"
version = "0.11"
description = "a curated set of instrument automation drivers implemented with labbench"

authors = [
    {name = "Dan Kuester", email = "daniel.kuester@nist.gov"},
    {name="Duncan McGillivray", email = "duncan.a.mcgillivray@nist.gov"  },
    {name="Andre Rosete", email = "andre.rosete@nist.gov" },
    {name="Paul Blanchard", email = "paul.blanchard@nist.gov" },
    {name="Michael Voecks", email = "michael.voecks@nist.gov" },
    {name="Ryan Jacobs", email = "ryan.jacobs@nist.gov" },
    {name="Alex Curtin", email =  "alexandra.curtin@nist.gov" },
    {name="Audrey Puls", email = "audrey.puls@nist.gov" },
    {name="John Ladbury", email = "john.ladbury@nist.gov" },
    {name="Yao Ma", email = "yao.ma@nist.gov" }
]

maintainers = [
    {name = "Dan Kuester", email = "daniel.kuester@nist.gov"},
]

dependencies = [
    "labbench>=0.23.4",
    "hidapi",
    "pywifi",
    "brainstem>=2.9.26",
]

requires-python = ">=3.8,<3.12"
readme = "README.md"
license = {file = "LICENSE.md"}

[project.urls]
homepage = "https://github.com/usnistgov/ssmdevices"
repository = "https://github.com/usnistgov/ssmdevices"
documentation = "https://pages.nist.gov/ssmdevices"

[build-system]
requires = [
    "pdm-pep517>=1.0",
]
build-backend = "pdm.pep517.api"

[tool]
[tool.pdm]

[tool.pdm.version]
source = "scm"
write_to = "ssmdevices/_version.py"
write_template = "__version__ = '{}'"

[tool.pdm.dev-dependencies]
dev = [
    "black[jupyter]",
    "ipython",
    "flake8",
    "ast_decompiler",
    "mypy",
    "pytest",
    "pytest-cov",
    "sphinx>=4.5",
    "recommonmark",
    "ipywidgets",
    "sphinx-autoapi>=2.1.0",
]

[tool.black]
line-length = 88
target-version = ["py38", "py39", "py310", "py311"]
include = '\.pyi?$'

[tool.pdm.scripts]
build-html = {cmd = "sphinx-build -b html doc public"}
build-latex = {cmd = "sphinx-build -b latex doc latex"}
build-rst = {cmd = "sphinx-apidoc -F . -o doc"}