import labbench as lb
from typing import Any


class MiniCircuitsUSBDevice(lb.Device):

    def __init__(self, resource: str='NoneType', usb_path: str='NoneType', timeout: str='int'):
        ...
    resource: Any = ...
    usb_path: Any = ...
    timeout: Any = ...

    @classmethod
    def __imports__(cls) -> None:
        ...
    backend: Any = ...

    def open(self) -> None:
        ...

    def close(self) -> None:
        ...


class SwitchAttenuatorBase(MiniCircuitsUSBDevice):

    def __init__(self, resource: str='NoneType', usb_path: str='NoneType', timeout: str='int'):
        ...
    CMD_GET_PART_NUMBER: int = ...
    CMD_GET_SERIAL_NUMBER: int = ...

    def model(self):
        ...

    def serial_number(self):
        ...
