import labbench as lb
from typing import Any, Optional


class RigolDP800Series(lb.VISADevice):

    def __init__(
        self,
        resource: str='str',
        read_termination: str='str',
        write_termination: str='str',
        local_variable: str='str'
    ):
        ...
    REMAP_BOOL: Any = ...
    local_variable: Any = ...
    enable1: Any = ...
    enable2: Any = ...
    enable3: Any = ...
    voltage_setting1: Any = ...
    voltage_setting2: Any = ...
    voltage_setting3: Any = ...
    voltage1: Any = ...
    voltage2: Any = ...
    voltage3: Any = ...
    current1: Any = ...
    current2: Any = ...
    current3: Any = ...

    def fetch_data_trace(self, whichone: Any):
        ...

    def open(self) -> None:
        ...

    def get_key(self, scpi_key: Any, trait_name: Optional[Any]=...):
        ...

    def set_key(self, scpi_key: Any, value: Any, trait_name: Optional[Any]=...):
        ...
