import labbench as lb
from typing import Any, Optional

class AcronameUSBHub2x4(lb.Device):
    def __init__(self, resource: str = "NoneType"): ...
    model: int = ...
    data0_enabled: Any = ...
    data1_enabled: Any = ...
    data2_enabled: Any = ...
    data3_enabled: Any = ...
    power0_enabled: Any = ...
    power1_enabled: Any = ...
    power2_enabled: Any = ...
    power3_enabled: Any = ...
    def __import__(self) -> None: ...
    backend: Any = ...
    def open(self) -> None: ...
    def close(self) -> None: ...
    def set_key(self, key: Any, value: Any, name: Optional[Any] = ...) -> None: ...
    def enable(
        self, data: bool = ..., power: bool = ..., channel: str = ...
    ) -> None: ...
